In [17]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.12.0+cu132


In [18]:
!nvidia-smi


Mon May 25 21:09:55 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 596.36                 Driver Version: 596.36         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8              4W /   50W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Introducing Tensors


### creating tensors

In [40]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [41]:
scalar.ndim


0

In [42]:
#get tensor back as python int
scalar.item()



7

In [43]:
#Vector
vector = torch.tensor([7,7])
vector



tensor([7, 7])

In [44]:
vector.ndim

1

In [45]:
vector.shape

torch.Size([2])

In [46]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX



tensor([[ 7,  8],
        [ 9, 10]])

In [47]:
MATRIX.ndim

2

In [48]:
MATRIX[1]#change dig to change dimension

tensor([ 9, 10])

In [49]:
MATRIX.shape

torch.Size([2, 2])

In [50]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [51]:
TENSOR.ndim

3

In [52]:
TENSOR.shape

torch.Size([1, 3, 3])

第一个1是(**[**[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]**]**)，
第二个3是有三个元素
第三个3是每个元素里有3个量

In [53]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

|Name|	What is it?|	Number of dimensions|	Lower or upper (usually/example)|
|-----|------|-------|-------------------------|
scalar|	a single number|	0|	Lower (a)|
|vector|	a number with direction (e.g. wind speed with direction) but can also have many other numbers|	1|	Lower (y)|
|matrix|	a 2-dimensional array of numbers|	2|	Upper (Q)|
|tensor|	an n-dimensional array of numbers|	can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector|	Upper (X)|

### Random Tensors

why random tensors?

Random tensors are important because many networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers->look at data->update random numbers->look at data->update random numbers`

In [63]:
#Create a random tensor of size(3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.4295, 0.6084, 0.5381, 0.7520],
         [0.5139, 0.0268, 0.0421, 0.1315],
         [0.6496, 0.5162, 0.6994, 0.0228]],

        [[0.7280, 0.5073, 0.2706, 0.1707],
         [0.5914, 0.5414, 0.4258, 0.2440],
         [0.0515, 0.0769, 0.0606, 0.3682]]])

In [61]:
random_tensor.ndim

3

In [69]:
#create a tensor with simliar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
# color channel(RGB),height, width
random_image_size_tensor#.shape, random_image_size_tensor.ndim



tensor([[[0.2408, 0.8393, 0.7200,  ..., 0.0978, 0.9946, 0.9964],
         [0.6129, 0.5297, 0.7359,  ..., 0.7777, 0.0450, 0.8661],
         [0.7053, 0.5230, 0.7498,  ..., 0.8264, 0.4433, 0.6142],
         ...,
         [0.5653, 0.3976, 0.6907,  ..., 0.6591, 0.2928, 0.9268],
         [0.9219, 0.2602, 0.0880,  ..., 0.5753, 0.8623, 0.2376],
         [0.7094, 0.3116, 0.4873,  ..., 0.3104, 0.0321, 0.8613]],

        [[0.4128, 0.6250, 0.9592,  ..., 0.1745, 0.4798, 0.4169],
         [0.7012, 0.2896, 0.7549,  ..., 0.2454, 0.4338, 0.7348],
         [0.2275, 0.5553, 0.8816,  ..., 0.0758, 0.1223, 0.7847],
         ...,
         [0.0600, 0.4931, 0.2751,  ..., 0.6106, 0.1591, 0.4627],
         [0.6133, 0.5854, 0.0513,  ..., 0.2473, 0.9649, 0.3586],
         [0.4315, 0.3973, 0.8744,  ..., 0.9760, 0.9325, 0.1039]],

        [[0.0027, 0.8975, 0.6552,  ..., 0.2199, 0.7600, 0.2436],
         [0.8377, 0.1610, 0.4245,  ..., 0.4688, 0.5707, 0.6944],
         [0.5090, 0.2865, 0.8831,  ..., 0.9307, 0.6859, 0.

In [86]:
random_tensor = torch.rand(size=(3,4,5))
random_tensor

tensor([[[0.0859, 0.9729, 0.5440, 0.4303, 0.9587],
         [0.7983, 0.7296, 0.2465, 0.1880, 0.2019],
         [0.4807, 0.1819, 0.1823, 0.1651, 0.2280],
         [0.9739, 0.0870, 0.0558, 0.2418, 0.9603]],

        [[0.9791, 0.4450, 0.8696, 0.7093, 0.7417],
         [0.4943, 0.2918, 0.6231, 0.9291, 0.8033],
         [0.5434, 0.3792, 0.6243, 0.0182, 0.6602],
         [0.8296, 0.3533, 0.7528, 0.4314, 0.7705]],

        [[0.9153, 0.6758, 0.0324, 0.7179, 0.5679],
         [0.0302, 0.5687, 0.1282, 0.7197, 0.7333],
         [0.1001, 0.2785, 0.0310, 0.8204, 0.3883],
         [0.0972, 0.4923, 0.8398, 0.9154, 0.0760]]])

### zero and one tensor


In [87]:
zero = torch.zeros(size=(3,4,5))
zero

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [88]:
zero*random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [93]:
# create a tensor of all ones
ones = torch.ones(size=(3,4,5))
ones

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

### creating a range of tensors and tensor_like


In [ ]:
#use torch.range() and get deprecated message, use torch.arange()instead
torch.range(0,11)

C:\Users\wangjianing\AppData\Local\Temp\ipykernel_31544\3905544846.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,11)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [100]:
one_to_thousand = torch.arange(start=0,end=1000,step=28)
one_to_thousand

tensor([  0,  28,  56,  84, 112, 140, 168, 196, 224, 252, 280, 308, 336, 364,
        392, 420, 448, 476, 504, 532, 560, 588, 616, 644, 672, 700, 728, 756,
        784, 812, 840, 868, 896, 924, 952, 980])

In [102]:
#tensor like
a_few_zeros = torch.zeros_like(input=one_to_thousand)
a_few_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

**note:** Tensor datatypes is one of 3 big errors you'll run into with pytorch & deep learning:
1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device


In [ ]:
#float 32
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,#datatype of the tensor(eg.float16,float32)
                               device="cuda",#
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype