In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.12.0+cu132


In [2]:
!nvidia-smi


Sun May 31 14:15:54 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 596.36                 Driver Version: 596.36         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8              1W /   30W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Introducing Tensors


### creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#get tensor back as python int
scalar.item()



7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector



tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX



tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]#change dig to change dimension

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

* 第一个1是(**[**[[1, 2, 3],
                [3, 6, 9],
               [2, 4, 5]]**]**)，
* 第二个3是有三个元素
* 第三个3是每个元素里有3个量
* 最后面的项指最里面的一层。以此类推，适用于n维的矩阵。

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

|Name|	What is it?|	Number of dimensions|	Lower or upper (usually/example)|
|-----|------|-------|-------------------------|
scalar|	a single number|	0|	Lower (a)|
|vector|	a number with direction (e.g. wind speed with direction) but can also have many other numbers|	1|	Lower (y)|
|matrix|	a 2-dimensional array of numbers|	2|	Upper (Q)|
|tensor|	an n-dimensional array of numbers|	can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector|	Upper (X)|

### Random Tensors

why random tensors?

Random tensors are important because many networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers->look at data->update random numbers->look at data->update random numbers`

In [17]:
#Create a random tensor of size(3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.9176, 0.4489, 0.7116, 0.5191],
         [0.7435, 0.7153, 0.6114, 0.1750],
         [0.6468, 0.8480, 0.8826, 0.1190]],

        [[0.7176, 0.7740, 0.1351, 0.5896],
         [0.5106, 0.5962, 0.9202, 0.9416],
         [0.7738, 0.2376, 0.7640, 0.0440]]])

In [18]:
random_tensor.ndim

3

In [19]:
#create a tensor with simliar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
# color channel(RGB),height, width
random_image_size_tensor#.shape, random_image_size_tensor.ndim



tensor([[[0.6209, 0.9803, 0.8122,  ..., 0.1235, 0.6489, 0.3424],
         [0.3806, 0.8731, 0.2408,  ..., 0.1341, 0.8372, 0.6595],
         [0.4523, 0.1595, 0.1930,  ..., 0.3841, 0.2147, 0.9075],
         ...,
         [0.3722, 0.5747, 0.3956,  ..., 0.9943, 0.4409, 0.5991],
         [0.8736, 0.6832, 0.9018,  ..., 0.8774, 0.5752, 0.4304],
         [0.9879, 0.3511, 0.9817,  ..., 0.4159, 0.8735, 0.0091]],

        [[0.1819, 0.9504, 0.7463,  ..., 0.4625, 0.9202, 0.6554],
         [0.8663, 0.2091, 0.1342,  ..., 0.6194, 0.3581, 0.3123],
         [0.0200, 0.8080, 0.3373,  ..., 0.5016, 0.5911, 0.4865],
         ...,
         [0.4533, 0.9717, 0.7221,  ..., 0.6660, 0.2188, 0.9216],
         [0.8304, 0.5653, 0.7657,  ..., 0.4267, 0.4016, 0.0533],
         [0.9848, 0.6698, 0.3440,  ..., 0.8881, 0.6685, 0.9636]],

        [[0.9868, 0.3200, 0.1322,  ..., 0.1316, 0.7351, 0.2573],
         [0.4814, 0.5140, 0.7511,  ..., 0.1766, 0.9205, 0.9124],
         [0.0664, 0.4590, 0.3929,  ..., 0.0306, 0.4013, 0.

In [20]:
random_tensor = torch.rand(size=(3,4,5))
random_tensor

tensor([[[9.9744e-01, 5.8109e-01, 7.8923e-01, 8.6751e-01, 1.2957e-01],
         [5.9486e-01, 9.3037e-02, 8.0527e-01, 8.7515e-01, 8.8504e-01],
         [9.3585e-02, 3.4136e-01, 4.6106e-01, 9.2808e-01, 9.5795e-01],
         [9.5396e-01, 4.1026e-04, 9.8261e-01, 7.0005e-01, 5.9129e-02]],

        [[4.2383e-01, 1.2206e-01, 9.0370e-01, 9.4451e-01, 3.4548e-01],
         [4.6425e-01, 6.6889e-01, 9.7668e-01, 4.8590e-01, 3.3863e-01],
         [2.2203e-01, 9.8929e-01, 9.6877e-01, 6.4796e-01, 9.1445e-02],
         [2.0518e-01, 5.9652e-01, 8.1418e-01, 2.6902e-01, 3.0370e-01]],

        [[3.2204e-03, 7.7514e-01, 4.2100e-01, 2.6690e-01, 8.4844e-02],
         [3.0836e-01, 2.9946e-01, 7.7496e-01, 3.6554e-01, 7.8224e-01],
         [1.2815e-01, 2.4981e-01, 9.5651e-01, 9.6707e-01, 3.7358e-01],
         [7.9191e-01, 2.1694e-01, 6.2499e-01, 3.6066e-01, 9.7447e-01]]])

### zero and one tensor


In [21]:
zero = torch.zeros(size=(3,4,5))
zero

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [22]:
zero*random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [23]:
# create a tensor of all ones
ones = torch.ones(size=(3,4,5))
ones

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

### creating a range of tensors and tensor_like


In [24]:
#use torch.range() and get deprecated message, use torch.arange()instead
torch.range(0,11)

C:\Users\wangjianing\AppData\Local\Temp\ipykernel_32120\1669414284.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,11)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [25]:
one_to_thousand = torch.arange(start=0,end=1000,step=28)
one_to_thousand

tensor([  0,  28,  56,  84, 112, 140, 168, 196, 224, 252, 280, 308, 336, 364,
        392, 420, 448, 476, 504, 532, 560, 588, 616, 644, 672, 700, 728, 756,
        784, 812, 840, 868, 896, 924, 952, 980])

In [26]:
#tensor like
a_few_zeros = torch.zeros_like(input=one_to_thousand)
a_few_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

**note:** Tensor datatypes is one of 3 big errors you'll run into with pytorch & deep learning:
1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device


In [27]:
#float 32
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,#datatype of the tensor(eg.float16,float32)
                               device="cuda",#what device is your tensor on (eg.cpu, gpu)
                               requires_grad=False)#whether or not to track the gradients for this tensors operations
                               
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor
#different type will lead uncertain issues
#so please do not try like this anymore

tensor([ 9., 36., 81.], device='cuda:0')

In [31]:
int_32_tensor = torch.tensor([3,6,9],dtype = torch.int32)
int_32_tensor


tensor([3, 6, 9], dtype=torch.int32)

### getting infos from tensor（tensor attributes）
 1. Tensors not right datatype - use `tensor.dtype` to get datatype
 2. Tensors not right shape: - to get shape from a tensor, use`tensor.shape`
 3. Tensors not omn the right device - use `tensor.device` to get device from tensor
 

In [32]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor


tensor([[0.6369, 0.9248, 0.8828, 0.3648],
        [0.8532, 0.6202, 0.8709, 0.3546],
        [0.4513, 0.1641, 0.6352, 0.5405]])

In [33]:
#Find out details about some tensor
print(some_tensor)
print(f"datatype:{some_tensor.dtype}")
print(f"shape:{some_tensor.shape}")
print(f"device:{some_tensor.device}")


tensor([[0.6369, 0.9248, 0.8828, 0.3648],
        [0.8532, 0.6202, 0.8709, 0.3546],
        [0.4513, 0.1641, 0.6352, 0.5405]])
datatype:torch.float32
shape:torch.Size([3, 4])
device:cpu


### manipulating tensors (tensor operation)

Tensor operations include:
* Addiction
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multipication

In [34]:
tensor = torch.tensor([1,2,3])
tensor + 100


tensor([101, 102, 103])

In [35]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
#subtract 10
tensor -10

tensor([-9, -8, -7])

In [37]:
#try inbuild funcs
torch.mul(tensor,10)


tensor([10, 20, 30])

In [38]:
torch.add(tensor,10)


tensor([11, 12, 13])

### Matrix muitlplication

two main ways of performing multiplication in neural networks and deep learning:

* Element-wise multiplication
* Matrix multiplication(dot product)


In [39]:
#Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals to {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals to tensor([1, 4, 9])


In [40]:
%%time
#Matrix multiplication

torch.matmul(tensor,tensor)
#what happens? a matrix multiplication defines so([1,2,3]*[1,2,3]=14)
#why? go back ask your linear algebra techaer

#use a torch verison(torch.xxx)to calculate instead of use python
#and write a for loop to save time


CPU times: total: 0 ns
Wall time: 1.5 ms


tensor(14)

### one of the most common errorss in deep learning:shape errors

there are 2 rules performing matrix mutliplication needs to satisfy:
1. the **inner dimension** must match(A的行等于B的列)
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. the resulting matrix has the shape of the **outer dimensions**（前矩阵第一行的列数）
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

* visit http://matrixmultiplication.xyz/ for more details


In [41]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))


tensor([[1.0964, 0.5697, 1.1652],
        [0.6571, 0.4790, 0.6114],
        [0.5878, 0.2527, 0.6580]])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.   

A **transpose** switches the axis or dimensions of a given tensor

In [42]:
Tensor_B = torch.tensor([[7,8,9],[10,11,12]])
Tensor_B,Tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [43]:
Tensor_B.T, Tensor_B.T.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

## Tensor aggregation(finding the min, max, mean, sum, etc)

In [44]:
#create and find the min
x = torch.arange(1,101,10)
torch.min(x),x.min()


(tensor(1), tensor(1))

In [45]:
#find the max
torch.max(x),x.max()


(tensor(91), tensor(91))

In [46]:
#find the mean
#torch.mean(x)直接写这句一定会报错
#could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [47]:
#find the sum
torch.sum(x),x.sum()



(tensor(460), tensor(460))

### Finding the positional min and the max


In [48]:
#argmin:最小张量值第一次出现的位置
x,x.argmin(),x[0]


(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), tensor(0), tensor(1))

In [49]:
#argmax
x,x.argmax(),x[9]#从0开始


(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), tensor(9), tensor(91))

## Reshaping,stacking,squeezing, and unsqueezing tensors

* reshaping: reshapes an input tensor to a defined shape
* View: Return a view of an input tensor of a certain shape but keep the same memory as the origional tensor
* stacking: combine multiple tensors on top of each other(vstack) or side by side(hstack)
* squeeze: remove all `1` dimensions from a tensor
* unsqueeze: add a `1`dimension to a target tensor
* Permute: return a view of the input with dimension permuted (swapped) in a certain way



In [50]:
#creating
import torch 
x = torch.arange(1.,13.)
x,x.shape


(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [51]:
#add an extra dimension
x_reshaped = x.reshape(1,12)
x_reshaped
#reshape以后的tensor的参数量必须与reshape之前的tensor的参数量相同。

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [52]:
#change the view
z = x.view(3,4)
z,z.shape
#z isn what x looks like they share the same memory
#so

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [53]:
#changes Z changes X(because a view of tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 5., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]))

In [54]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked



tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]])

In [55]:
#squeeze_remove all single dimensions from tensor
#like:torch.size(2,1,2,1,2)->torch.size(2,2,2)
x_reshaped.squeeze().shape
#clear the 1


torch.Size([12])

In [56]:
x_squeezed = x_reshaped.squeeze()
#会发现，输出的结果少了一个括号。
x_squeezed

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.])

In [57]:
print(f"Previous: {x_reshaped}")
print(f"  New   : {x_reshaped.squeeze()}")


Previous: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]])
  New   : tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.])


In [58]:
#unsqueeze: adds a single to a target tensor at a specific dim
print(f"Previous: {x_squeezed}")
print(f"  Now   : {x_squeezed.unsqueeze(dim=0)}")
#在dim=0上unsqueeze。也可以在dim=1上unsqueeze。


Previous: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.])
  Now   : tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]])


|名称	|ndim (阶)	|可用 dim|
|------|------|------|
|标量 (scalar)|	0	|无|
|向量 (vector)|	1|	0|
|矩阵 (matrix)	|2	|0, 1|
|3D张量	|3|	0, 1, 2|
|nD张量|	n|	0, 1, ..., n-1|

数学上，一个 `ndim=n` 的张量有 n 个轴 (axis) 或模 (mode)。每个轴编号从 0 到 n-1。`dim=k` 的意思是"沿着第 k 个轴进行缩减（reduction）"，操作后该轴被消除，张量的阶数减少 1。  

所以：   

* 一个 2D 矩阵 只有轴0（行方向）和轴1（列方向），没有轴2
* 操作 `sum(dim=2)` 相当于要求"在第3个轴的方向上求和"——但这个轴根本不存在

In [62]:
#torch.permute: rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3))#height, width, color channels
#permute to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1)#shift axis original to now:0 to 1,1 to 2, 2 to 0

print(f"Previous:{x_original.shape}")
print(f"  Now   :{x_permuted.shape}")


Previous:torch.Size([224, 224, 3])
  Now   :torch.Size([3, 224, 224])


In [66]:
x_original[0,0,0] = 123211
x_original[0,0,0], x_permuted[0,0,0]


(tensor(123211.), tensor(123211.))

## Indexingf(selecting data from tensors)

indexing with Pytorch is simliar to indexing with numpy


In [70]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
#index new tensor
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
#index on the middle bracket
x[0][0]


tensor([1, 2, 3])

In [78]:
#index on the most inner bracket(last dim)
x[0,1,0]



tensor(1)

In [77]:
x[0,1,1]
#the ist dimention must 0 because we set it to (1,3,3)


tensor(5)

In [80]:
#use ":" to select "all" of a target dim
x[:,0]


tensor([[1, 2, 3]])

In [81]:
#get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]


tensor([[2, 5, 8]])

In [82]:
# get all valves of the 0 dimension but only the 1 index valve of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [83]:
#get index 0 of 0th and 1st dim and all valves of 2nd dim
x[0,0,:]


tensor([1, 2, 3])

In [84]:
#index on x to return 9
print(x[:,2,2])
#index on x to return 3,6,9
print(x[:,:,2])

tensor([9])
tensor([[3, 6, 9]])


## Pytorch and numpy

numpy is a scientific Python numerical computing library   
because of this, Pytorch has functionality to intract with it
* data in numpy,want in pytorch tensor -> `torch.from_numpy(tensor)`
* Pytorch tensor -> Numpy ->`torch.Tensor.numpy()`

In [86]:
#numpy array to tensor   
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)#converting from numpy ->pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
#change the valve of array, what will this do to tensor?
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
#default data type of pytorch is float 32

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [89]:
#change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:  
`start with random numbers -> tensor operations -> uodate random numbers to try and make them better representations of the data -> again ->again -> again`   

to reduce the randomness in nureon networks and pytorch comes the concept of a **random seed**   

Essentlly what the random seed does is "flavour" the randomness   


In [90]:
torch.rand(3,3)


tensor([[0.4171, 0.9086, 0.7084],
        [0.7368, 0.0305, 0.3619],
        [0.7008, 0.4460, 0.6723]])

In [92]:
import torch

#create two ranodm tensors
randomA = torch.rand(3,4)
randomB = torch.rand(3,4)
print(randomA)
print(randomB)
print(randomA == randomB)


tensor([[0.9060, 0.5954, 0.8401, 0.5157],
        [0.5068, 0.5335, 0.6525, 0.2846],
        [0.3958, 0.8632, 0.0998, 0.8616]])
tensor([[0.4330, 0.2113, 0.1260, 0.1551],
        [0.4210, 0.4270, 0.6862, 0.3098],
        [0.4897, 0.4978, 0.7812, 0.8295]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [93]:
1 == 1



True

In [ ]:
#make some random but reproducible tensor
import torch

#set thr random seed
RANDOM_SEED = 123456
torch.manual_seed(RANDOM_SEED)
randomC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randomD = torch.rand(3,4)

#every time reproduce a random seed
print(randomC == randomD)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## running objects on GPU making faster computation

GPU fast compute   
thanks CUDA


### I already have a GPU


In [101]:
!nvidia-smi


Sun May 31 19:31:23 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 596.36                 Driver Version: 596.36         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8              3W /   50W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [102]:
#check out gpu
import torch
torch.cuda.is_available()

True

it's best practice to set up a device agnostic code for pytorch since it's capable of running in cpu or gpu

In [ ]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [104]:
#count num of device
torch.cuda.device_count()

1

## putting tensors(and models) on GPU

the reason we want our tensors on the GPU is because GPU results in faster computations


In [106]:
#create(defult on CPU)
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [108]:
#move tensor(if GPU avaliable)
tensor_on_GPU = tensor.to(device)
tensor_on_GPU
#we create a device variable and we use this to transform whether to use


tensor([1, 2, 3], device='cuda:0')

### moving tensor back to cpu


In [113]:
#now tensor is on gpu
#tensor_on_GPU.numpy() will wrong
#can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
tensor_on_CPU = tensor_on_GPU.cpu().numpy()
tensor_on_CPU, tensor_on_CPU.device

(array([1, 2, 3]), 'cpu')

## Exercises (may be later)
check https://learnpytorch.io/00_pytorch_fundamentals/#exercises to get these resources